apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        name: flux-bot
        email: flux-bot@dev.test
      messageTemplate: |-
        chore: update staging images (flux image automation)
        {{ range .Updated.Images }}
        - {{ . }}
        {{- end}}
  update:
    path: ./apps/staging
    strategy: Setters
