apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metabase
  namespace: metabase
spec:
  chart:
    spec:
      version: "1.0.3"
  test:
    enable: false
  values:
    image:
      tag: v0.44.0
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: mb.staging.com
